version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_api
    restart: always
    env_file:
      - "./.env"
    command: "uvicorn api.main:api --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/api
    networks:
      - fastapi-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: fastapi_postgres
    restart: always
    env_file:
      - "./.env"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    networks:
      - fastapi-network

  adminer:
    image: adminer
    container_name: fastapi_adminer
    restart: always
    ports:
      - "8080:8080"

networks:
  fastapi-network:
    driver: bridge

volumes:
  data:
